models/ForumTopic.php
<?php
/**
 * ForumTopic class file.
 *
 * @author Ismail <is.tmdg86@gmail.com>
 * @since 2017.10.20 
 */

namespace app\models;

use app\models\User;
use app\models\queries\ForumTopicQuery;
use Yii;

/**
 * This is the model class for table "ForumTopics".
 *
 * @author Ismail <is.tmdg86@gmail.com>
 * @since 2017.10.20 
 */
class ForumTopic extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     * @return string
     */
    public static function tableName()
    {
        return 'ForumTopics';
    }
    
    public function behaviors()
    {
      return [
            'comments' => [
                'class' => 'yeesoft\comments\behaviors\CommentsBehavior'
            ]
        ];
    }
    /**
     * @inheritdoc
     * @return array
     */
    public function rules()
    {
        return [
            [['categoryId', 'title', 'detail'], 'required'],
            [['userId', 'isRemoved', 'createdBy', 'updatedBy'], 'integer'],
            [['title', 'detail'], 'string'],
            [['removedTime', 'createdTime', 'updatedTime'], 'safe'],
            [['title'], 'string', 'max' => 255]
        ];
    }
    
    /**
     * @inheritdoc
     * @return attribute label on topic form
     */
    public function attributeLabels()
    {
        return [
            'categoryId' => 'Category',
        ];
    }

    /**
     * @inheritdoc
     * @return UserTestimonyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ForumTopicQuery(get_called_class());
    }
    
    /**
     * @return queries\ForumCategoryActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(ForumCategory::class, ['id' => 'categoryId']);
    }
    
    public function getAuthor()
    {
        $user = User::findOne(['id' => $this->userId]);
        if ($user) {
            return $user->username;
        }
        return null;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ForumCategory;
use app\models\ForumTopic;
use app\models\forms\LoginForm;
use app\models\forms\SignupForm;
use yii\data\ActiveDataProvider;
use Yii;
use yii\web\Controller;
use yii\web\Response;

class SiteController extends Controller
{
    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex($categoryId = null)
    {
        $categories = ForumCategory::find()->all();
        
        if ($categoryId !== null) {
            $query = ForumTopic::find()
                ->andWhereCategoryId($categoryId)
                ->andWhereIsNotRemoved();
        } else {
            $query = ForumTopic::find()
                ->andWhereIsNotRemoved();
        }
            
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => ['pageSize' => 5],
            'sort' => [
                'defaultOrder' => [
                    'createdTime' => SORT_DESC
                ]
            ]
        ]);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'categories' => $categories
        ]);
    }
    
    /*
     * Detail page.
     */
    public function actionDetail($id)
    {
        $model = ForumTopic::findOne(['id' => $id]);
        
        return $this->render('detail-post', [
            'model' => $model
        ]);
    }

    /**
     * Create new post.
     * @return string
     */
    public function actionCreatePost()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        $model = new ForumTopic();
        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($model->save()) {
                Yii::$app->getSession()->setFlash('createSuccess');
                $userId = Yii::$app->user->id;
                return $this->redirect(['account', 'id' => $userId]);
            }
        }
        return $this->render('new-post', [
            'model' => $model
        ]);
    }
    
    /*
     * Update posted topic.
     */
    public function actionUpdate($id)
    {
        $model = ForumTopic::findOne(['id' => $id]);
        
        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($model->save()) {
                Yii::$app->getSession()->setFlash('createSuccess');
                $userId = Yii::$app->user->id;
                return $this->redirect(['account', 'id' => $userId]);
            }
        }
        return $this->render('new-post', [
            'model' => $model
        ]);
    }

    /*
     * User Account.
     */
    public function actionAccount($id, $categoryId = null)
    {
        if ($categoryId !== null) {
            $query = ForumTopic::find()
                ->andWhereUserId($id)
                ->andWhereCategoryId($categoryId)
                ->andWhereIsNotRemoved();
        } else {
            $query = ForumTopic::find()
                ->andWhereUserId($id)
                ->andWhereIsNotRemoved();
        }

        $categories = ForumCategory::find()->all();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => ['pageSize' => 5],
            'sort' => [
                'defaultOrder' => [
                    'createdTime' => SORT_DESC
                ]
            ]
        ]);
        return $this->render('account', [
            'dataProvider' => $dataProvider,
            'categories' => $categories
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $userId = Yii::$app->user->id;
            return $this->redirect(['account', 'id' => $userId]);
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }
    
    public function actionSignup()
    {
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post()) && ($user = $model->signup())
            && Yii::$app->getUser()->login($user)) {
            return $this->redirect(['account', 'id' => $user->id]);
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}

views/site/_category.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;

$userId = Yii::$app->user->id;
        
?>

<div class="list-group">
    
    <a href="<?= Yii::$app->user->isGuest ? 'index' : 'account?id=' . $userId ?>" class="list-group-item">All Categories</a>
    <?php foreach ($categories as $value): ?>
        <?php if (Yii::$app->user->isGuest) : ?>
            <?= Html::a($value->category, ['index', 'categoryId' => $value->id], ['class' => 'list-group-item']) ?>
        <?php else : ?> 
            <?= Html::a($value->category, ['account', 'id' => $userId, 'categoryId' => $value->id], ['class' => 'list-group-item']) ?>
        <?php endif; ?>
    <?php endforeach; ?>
</div>

views/site/_listItem.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
use yii\helpers\Url;

?>

<div class="list-item">
    <div class="col-md-10">
        <?= Html::a($model->title,
            ['detail', 'id' => $model->id])
        ?>
    </div>
    <div class="col-md-2">
        <?php if (!Yii::$app->user->isGuest) :?>
        <?= Html::a('edit', 
            ['update', 'id' => $model->id],
            ['class' => 'btn btn-default btn-xs pull-right']) 
        ?>
        <?php endif; ?>
    </div>
    <div class="list-item-author">
        <ul>
            <li><?= Html::a('Category : ' . $model->category->category)?></li>
            <li><?= Html::a('Publisher : ' . $model->getAuthor())?></li>
        </ul>
    </div>
</div>

views/site/account.php
<?php
/* @var $this yii\web\View */

use yii\bootstrap\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

$this->title = 'Account';
?>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <?= Html::a(
                'Create Post',
                ['create-post'],
                [
                    'class' => 'btn btn-primary pull-right',
                ]
            ); ?>
        </div>
    </div>
    <div class="row pt30">
        <div class="col-md-3">
            <?= $this->render('_category', [
                'categories' => $categories
            ]) ?>
        </div>
        <div class="col-md-8">
            <?php if (Yii::$app->getSession()->getFlash('createSuccess')): ?>
                <div class="panel-toolbar-wrapper">
                    <div class="alert alert-success fade in">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h4 class="semibold"><?= Yii::t('app', 'Create Success') ?></h4>
                        <p class="mb10"><?= Yii::t('app', 'Item was successfully post new topic.') ?></p>
                    </div>
                </div>
            <?php endif; ?>
            <div class="listing-header">Forum Listing</div>
                <?= ListView::widget([
                    'dataProvider' => $dataProvider,
                    'layout' => "{items}\n{pager}\n{summary}",
                    'itemView' => function ($model) {
                        return $this->render('_listItem',['model' => $model]);
                    },
                ])?>
            </div>
    </div>
</section>

views/site/detail-post.php
<?php
/* @var $this yii\web\View */

use yeesoft\comments\widgets\Comments;

$this->title = 'Detail Post - ' . ($model->title ? $model->title : '');

?>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><?= $model->title ?></div>
  <div class="panel-body">
    <?= $model->detail ?>
  </div>
</div>
<div class="col-md-12">
    <?= Comments::widget([
        'model' => 'post',
        'model_id' => $model->id
    ]) ?>
</div>

views/site/index.php
<?php
/* @var $this yii\web\View */

use yii\bootstrap\Html;
use yii\helpers\Url;
use yii\widgets\ListView;

$this->title = 'Game Forum';
?>

<section class="content">
    <div class="row pt30">
        <div class="col-md-3">
            <?= $this->render('_category', [
                'categories' => $categories
            ]) ?>
        </div>
        <div class="col-md-8">
            <div class="listing-header">Forum Listing</div>
                <?= ListView::widget([
                    'dataProvider' => $dataProvider,
                    'layout' => "{items}\n{pager}\n{summary}",
                    'itemView' => function ($model) {
                        return $this->render('_listItem',['model' => $model]);
                    },
                ])?>
            </div>
    </div>
</section>

views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
?>

<section>
    <!-- START row -->
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                <!-- Brand -->
                <div class="text-center">
                    <h3 class=""><?= Yii::t('app', 'Login') ?></h3>
                </div>
                <div class="row">
                    <!-- Login form -->
                    <div class="col-md-12">
                        <?php $form = ActiveForm::begin(['method' => 'post']) ?>
                        <div class="col-md-6 col-sm-6">
                            <?= $form->field($model, 'email')->textInput() ?>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <?= $form->field($model, 'password')->passwordInput() ?>
                        </div>
                        <div class="col-md-12 col-sm-12 pull-right">
                            <?= Html::submitButton('Login', ['class' => 'btn btn-primary']) ?>
                        </div>
                        <?php ActiveForm::end() ?>
                    </div>
                    <!-- Login form -->
                </div>
                <div class="row ">
                    <div class="col-md-12 pt30">
                        <?= Yii::t('app', 'New User?') ?>
                        <?= Html::a(Yii::t('app', 'Sign up'), ['signup']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ END row -->
</section>
<!--/ END Template Container -->

views/site/new-post.php
<?php
/* @var $this yii\web\View */

use app\models\ForumCategory;
use dosamigos\ckeditor\CKEditor;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'New Post';

$model->userId = Yii::$app->user->id;
?>

<section class="content">
    <div class="row">
        <div class="col-md-12 content-right pl0">
            <h2 class="title-page">
                Post New Topic
            </h2>
            <div class="col-md-7 enquire-form-item">
                <?php $form = ActiveForm::begin(); ?>
                <div style="display: none">
                    <?= $form->field($model, 'userId')->hiddenInput()->label(false); ?>
                </div>
                <div class="form-group ">
                    <?= $form->field($model, 'title')->textInput(['placeholder' => Yii::t('app', 'Topic title'), 'class' => 'form-control'])->label(null, ['class' => 'control-label']); ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'categoryId')->dropDownList(ForumCategory::getCategories(), [
                        'prompt' => 'Choose Category',
                    ]);?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'detail')->widget(CKEditor::className(), [
                        'options' => ['rows' => 6],
                        'preset' => 'basic'
                    ]) ?>
                </div>
                <div class="form-group right">
                    <?= Html::submitButton(Yii::t('app', 'Post Now'), ['class' => 'btn btn-primary']); ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</section>

views/site/signup.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
?>

<section>
    <!-- START row -->
    <div class="row">
        <div class="col-md-12">
            <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                <!-- Brand -->
                <div class="text-center">
                    <h3 class=""><?= Yii::t('app', 'Sign Up') ?></h3>
                </div>
                <div class="row">
                    <!-- Login form -->
                    <div class="col-md-12">
                        <?php $form = ActiveForm::begin(['method' => 'post']) ?>
                        <div class="col-md-6 col-sm-6">
                            <?= $form->field($model, 'username')->textInput() ?>
                            <?= $form->field($model, 'email')->textInput() ?>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <?= $form->field($model, 'password')->passwordInput() ?>
                            <?= $form->field($model, 'confirmPassword')->passwordInput() ?>
                        </div>
                        <div class="col-md-12 col-sm-12">
                            <?= Html::submitButton('Sign Up', ['class' => 'btn btn-primary']) ?>
                        </div>
                        <?php ActiveForm::end() ?>
                    </div>
                    <!-- Login form -->
                </div>
                <div class="row ">
                    <div class="col-md-12 pt30">
                        <?= Yii::t('app', 'Already have an Account') ?>
                        <?= Html::a(Yii::t('app', 'Login'), ['login']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ END row -->
</section>
<!--/ END Template Container -->